# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-06 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='submitted',
            new_name='created',
        ),
    ]
